#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yosuke sakamoto
# SPDX-License-Identifier: BSD-3-Clause

import sys

a = 10 - 70
print(a)

a = 100 ** 2
print(a)

a = 18 / 6
print(a)

a = 20 // 3
print(a)

a = 19 % 7
print(a)


